baseURL: https://ch-naseem.com/
languageCode: en-us
build:
  writeStats: true
params:
  title: naseem's portfolio
  author: Naseem Chettah
  description: naseem's portfolio
  copyright: >-
    © 2024 - 2025 Naseem · [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Naseem Chettah"
    tagline: IT Student
    location: "M'sila, Algeria"
    photo: profile2.jpg
    photo2: profile2.jpg
  social:
    title: Links
    list:
      - icon: fa fa-envelope
        url: "mailto:contact@ch-naseem.com"
        title: Email
      - icon: fab fa-linkedin
        url: "https://linkedin.ch-naseem.com"
        title: Linkedin
      - icon: fab fa-telegram
        url: "https://telegram.ch-naseem.com"
        title: Telegram
      - icon: fab fa-facebook
        url: "https://fb.ch-naseem.com"
        title: Facebook
      - icon: fab fa-github
        url: "https://github.ch-naseem.com"
        title: GitHub
      - icon: fa fa-code-branch fa-sm
        url: "https://git.ch-naseem.com"
        title: Code
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: My name is Naseem, and I am from Algeria! Welcome to my personal web page.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Computer Repair
        dates: 2019 - 2022
        company: KIM Tech
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: B.T.S. in Computer Science
        college: INSFP M'sila
        dates: 2023 - 2025
        thesis_title: "Design and implementation of an electronic medical records platform"
        thesis_url: "#"
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Rhazes EMR
        url: "https://rhazesemr.info"
        description: ...
      - title: The Oxidized Airport
        url: "https://github.com/ndpm13/oxidized-airport"
        description: a school project where I'll be using Tauri and ~~SurrealDB~~ PostgreSQL to create a nice application to book flights and airport stuff.
      - title: Al Kindi
        url: "https://github.com/ndpm13/Al-Kindi"
        description: Al-Kindi Convertor is a simple app I wrote to help my classmates convert values in the numeric bases BIN, OCT, DEC and HEX.
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Oracle DBMS
        skillrating: 80
      - skill: Desktop Applications (Tauri, C#, Delphi)
        skillrating: 85
      - skill: Backend Development (LAMP, Golang)
        skillrating: 60
      - skill: Prompt Engineering
        skillrating: 90
      - skill: GNU/Linux Administration
        skillrating: 70
      - skill: Data Entry and Management
        skillrating: 90
      - skill: Document Formatting and Markup
        skillrating: 70
      - skill: Scripting (Rust, BASH)
        skillrating: 90
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Coding
      - hobby: GNU/Linux
      - hobby: Blackwork design
      - hobby: Writing/Reading
